apiVersion: 1

datasources:
  - name: prometheus-main
    type: prometheus
    uid: prometheus-main
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: postgres-main
    type: grafana-postgresql-datasource
    access: proxy
    url: database_postgres:5432
    user: username
    uid: postgres-main
    jsonData:
      database: ml_data
      sslmode: disable
      postgresVersion: 1800
      timescaledb: false
    secureJsonData:
      password: password
    editable: false